services:
  - type: web
    name: brain-tumor-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    healthCheckPath: /
    healthCheckTimeout: 100
    staticPublishPath: /static
    buildEnvVars:
      - key: PYTHON_PACKAGES_PATH
        value: /opt/render/project/src/.packages
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: DATABASE_URL
        value: sqlite:///instance/users.db
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 1
    autoDeploy: true 